language: node_js
node_js:
    - "12"
    - "11"

addons:
  sonarcloud:
    organization: "unknownskl-github"

script:
  - npm test
  - sonar-scanner

before_install:
  - sudo apt-get -y install python-pip python-dev
  - sudo pip install -U setuptools
  - sudo pip install -U virtualenvwrapper
  - sudo pip install cryptography
  - python -V
